<HTML>
<BODY>
<B>ENTER YOUR PERSONAL DETAILS</B>
<FORM METHOD=GET ACTION="Details.php">
    FIRST NAME: <INPUT NAME:"nltext" TYPE="TEXT"><BR>
    LAST NAME: <INPUT NAME="n2text" TYPE="TEXT"><BR>
    ADDRESS: <TEXTAREA NAME."n3text" ROWS=1, COLUMNS=1000></TEXTAREA <BR> CONTACT NO:
    <INPUT NAME="n4text" TYPE="TEXT"><br>
    <INPUT TYPE="SUBMIT" NAME="SUBMIT" VALUE="SUBMIT">
</FORM>
</BODY>
</HTML>
